language: python
sudo: false

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
python:
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"

notifications:
  email:
    recipients:
      - jtonye@ymail.com

env:
  - DJANGO_SETTINGS_MODULE=django_view_breadcrumbs.settings

install:
  - pip install -e .'[test]' -r requirements.txt

script:
  - tox
