language: python
sudo: false
cache: pip
matrix:
  include:
  - python: 3.5
    env: TOXENV=ALL
  - python: 3.5-dev
    env: TOXENV=ALL
  - python: 3.6
    env: TOXENV=ALL
  - python: 3.6-dev
    env: TOXENV=ALL
  - python: 3.9-dev
    env: TOXENV=ALL
  - python: 3.8
    env: TOXENV=ALL
  - python: 3.7
    env: TOXENV=ALL
  - python: pypy3
    env: TOXENV=ALL
notifications:
  email:
    recipients:
    - jtonye@ymail.com
env:
  matrix:
  - DJANGO_SETTINGS_MODULE=django_view_breadcrumbs.settings
  global:
    secure: 0Tp5EqGa/4wJ3ETFSUVpLsLaX+Nhi3QNmm0+psnZ6f7i0RPUx9WG5YMfhIZuHEXfv7gZ+kts5G23SGAB5r7saZeDfjA3o4SoT4y5B0GHrwO/kUPJeQmh7Ysp4oUS71yNgi/VH3wFd++t5H05VQIl3yqqhUosIgTXtCOZJXwFnH5dvyE0Ek5TEl+JwKa5byxciST+Iu3FIpz8yddcYEV60eqLVULV+nD+htewrPTm2L5+mcAeQuEqq0DbU42Prgz1kvPnlLv/Ls50i/UQ8qAMQZrVeOsEJ0SS0VpAWzf6MX7EjXjSi8M53rQkbK/pouQvoZ1Lf9D3HFaSYRtJkKE74tJjacv5rp9KZ7tBVEWJ2PIw5d19MSjNH4OhTz4IjxNgxNzl7fVFgNwi4GXG/1s2lUx+fQySaldEFsPaHljZqdDPWj7XINltLs7j6VdBkkarya3569wjjLG3pPrHPrK0u56dQnH6EsUpfS8offTInFJKFcO1PlHk9nhV4kPyFv4KD9rf4OlidqByUw28Qv1sFvTHLvPt5nm/S02GEbq4G4muLHaFusNuct12+Y2Gb2Tr8UnY0OCkcz4faXKkVf7bUOg6sv7OquAP9439WqfZGzvBj+85G9nzpQJEgHm+uTVI0Zos1wl+uqMKl3PcWcCImMUo9y/c9QdT5IGLiOtGpC4=
install:
- make install-test
script:
- tox
addons:
  apt:
    update: true
    sources:
    - travis-ci/sqlite3
    packages:
    - sqlite3
