language: python
sudo: enabled

notifications:
  email:
    recipients:
      - jtonye@ymail.com

env:
  - DJANGO_SETTINGS_MODULE=django_view_breadcrumbs.settings

install:
  - pip install -e .[test] -r requirements.txt

script:
  - tox
