name: Auto PR
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

jobs:
  pull-request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: pull-request-develop-staging
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "master"
          destination_branch: "develop"
          pr_title: "Master → Develop."
          pr_body: ":white_check_mark: *Automated PR* (Changes on master branch to be merged into develop)"
          pr_reviewer: "jackton1"
          github_token: ${{ secrets.GITHUB_TOKEN }}
